server:
  port: 8888
netty:
  port: 10012
  host: 127.0.0.1
spring:
  redis:
    host: 192.168.21.60
    port: 6379
    database: 2
    timeout: 35
  datasource:
    url: jdbc:mysql://192.168.21.60:3306/robothost?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: Aa123456.com
    type: com.alibaba.druid.pool.DruidDataSource
    driverClassName: com.mysql.jdbc.Driver
    logSlowSql: true
    # Druid StatViewServlet配置

#SQL 打印
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: classpath*:mapper/**/*.xml


#ftp连接信息
ftpHost: 192.168.101.226
ftpPort: 21
ftpUsername: IntoRobot
ftpPassword: Aa123456