server:
  port: 8888
netty:
  port: 10011
  host: 192.168.199.142
spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/smart_ele_robot?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: 12345
    type: com.alibaba.druid.pool.DruidDataSource
    driverClassName: com.mysql.jdbc.Driver

#SQL 打印
#mybatis-plus:
#  configuration:
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
#  mapper-locations: classpath*:mapper/**/*.xml


#ftp连接信息
ftpHost: 192.168.199.142
ftpPort: 801
ftpUsername: ftpuser
ftpPassword: ftp123